---
title: "HW1"
author: "Aaron Coates"
date: "4/17/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Documents/GitHub/MMSS_311_2")
sick <- read.csv("/Users/aaroncoates/Downloads/sick_data.csv")

library(dplyr)
library(ggplot2)
library(glmnet)
library(broom)
library(aod)
```

```{r}
sick$result.d <- sapply(sick$result, function(x){
  if(x == "Positive"){
    1
  } else {
    0
  }})
```

```{r}
regOLS <- glm(result.d ~ temp + bp, data=sick) %>% broom::tidy()
for (i in 1:1000) {sick$predictionOLS[i] <- regOLS[1, 2] + regOLS[2, 2]*sick$temp[i] + regOLS[3,2]*sick$bp[i]}
```

```{r}
sum(with(sick, result.d==1 & predictionOLS>=.5))
sum(with(sick, result.d==1 & predictionOLS<=.5))
sum(with(sick, result.d==0 & predictionOLS>=.5))
sum(with(sick, result.d==0 & predictionOLS<=.5))
```

```{r}
intOLS <- (regOLS[1, 2] -.5)/(-regOLS[3, 2]) 
slopeyOLS <- regOLS[2, 2]/(-regOLS[3,2])
```

```{r}
plotOLS <- ggplot(data = sick, aes(x = temp, y = bp, col=result)) + geom_point() + geom_abline(intercept = intOLS[1, 1], slope = slopeyOLS[1, 1]) + labs(title ="OLS", x = "Temperature", y = "Blood Pressure")
```

```{r, echo=FALSE}
plotOLS
```

```{r}
sick$result <- factor(sick$result)
logit <- glm(result ~ temp + bp, data = sick, family = "binomial") %>% broom::tidy()
for (i in 1:1000) {sick$predictionLOGIT[i] <- logit[1, 2] + logit[2, 2]*sick$temp[i] + logit[3,2]*sick$bp[i]}
```

```{r}
sum(with(sick, result.d==1 & predictionLOGIT>=.5))
sum(with(sick, result.d==1 & predictionLOGIT<=.5))
sum(with(sick, result.d==0 & predictionLOGIT>=.5))
sum(with(sick, result.d==0 & predictionLOGIT<=.5))
```

```{r}
intLOG <- (logit[1, 2] -.5)/(-logit[3, 2]) 
slopeyLOG <- logit[2, 2]/(-logit[3,2])
```

```{r}
plotLOG <- ggplot(data = sick, aes(x = temp, y = bp, col=result)) + geom_point() + geom_abline(intercept = intLOG[1, 1], slope = slopeyLOG[1, 1]) + labs(title ="Logit", x = "Temperature", y = "Blood Pressure")
```

```{r, echo=FALSE}
plotLOG
```

