setwd("~/Documents/GitHub/MMSS_311_2")
install.packages('dplyr')
install.packages('ggplot2')
install.packages('stringr')
install.packages('lubridate')
library('dplyr')
library('ggplot2')
library('stringr')
library('lubridate')
qog <- read_csv("~/Documents/GitHub/qpg.csv")
print(dim(qog))

